### PR TITLE
Add light version of logo image template

### PR DESCRIPTION
**Pull request by henning-roos**
### Applicable Issues
https://github.com/eiffel-community/eiffel-repository-template/issues/2

### Description of the Change
  * Add light version of logo image template designed to be used for dark backgrounds

  * Restructure layers into layer groups in xcf image for easier navigation
    and so that it is possible to hide/unhide whole version at the same time

### Alternate Designs
No alternate design provided.

### Benefits
The community may need a light version of the eiffel logos in the future.

### Possible Drawbacks
None perceived

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Henning Roos   henning.roos@ericsson.com

### CODE REVIEW

**Comment by roos-ericsson** [comment]
@d-stahl-ericsson I could not add you as a reviewer. Don't know why. I hope you get a notification this way instead.

**Comment by henning-roos** [comment]
@d-stahl-ericsson Have you had time to take a look on this yet?

**Comment by henning-roos** [comment]
@eiffel-community/eiffel-community-maintainers  is it OK to merge this PR?

**Review by e-backmark-ericsson — APPROVED** [review]
I'd say the update looks good. This logo template should probably not be in the template repo when the new community repo structure is finalized, as it would be copied into all new community repos then, but as long as it stays here I think the new image structure is good.

**Pull request merged**
